### ISSUE TITLE
Improve error reporting in Diplomat

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#110]
We need to:

 - [ ] [Be testing our errors](https://github.com/rust-diplomat/diplomat/issues/107)
 - [ ] [Use proper error enums](https://github.com/rust-diplomat/diplomat/issues/new)
 - [ ] [Have nicer formatted errors](https://github.com/rust-diplomat/diplomat/issues/109)
 - [ ] [Have file/line info in our errors](https://github.com/rust-diplomat/diplomat/issues/111)

**Comment by Manishearth** [comment]
https://github.com/rust-diplomat/diplomat/issues/111 is the only open one left, it's the more specific one anyway
