### ISSUE TITLE
Create a higher level intermediate representation

### ISSUE THREAD

**Issue by QnnOkabayashi** [rust-diplomat/diplomat#204]
# Proposal

Diplomat's current understanding of types in `diplomat_core::ast` is very loose, and allows for representing states that are disallowed in Diplomat's model. While we have validity checks, they do nothing to prove that types are valid at the type level, meaning that backend code is often bloated with `unwrap()` and `unreachable!()`. We should create an HIR that enforces the invariants that we can lower the AST to before passing it to a backend. This will help make the backend significantly cleaner, since all the invariants will be enforced at the type level.

# Roadmap

- [x] Strictly define what is and isn't allowed in Diplomat's model.
  * Input/output types? What Rust types are allowed?
- [x] Create `diplomat_core::hir` module with only type definitions reflecting the model.
- [x] Implement functionality, e.g. lowering from AST which would replace validity checks.
- [ ] Integrate with backends. (https://github.com/rust-diplomat/diplomat/issues/252)

# Goals

* Make invalid states unrepresentable.
* Make HIR types considerate to all languages:
  * For example, not all primitives should be treated the same. `char` and `bool` are their own thing, and many languages don't support 128-bit numbers. So instead of an umbrella `Primitive` enum for everything at the top level, it would have variants like `Int` (8, 16, 32, 64 un/signed ints), `Int128` (`i128`/`u128`), `Char`, and `Bool`.
* Make lifetime tracking down the type tree and through structs (which may have differently named lifetimes) a top consideration so we don't need to have language-specific implementations. Currently, JS does its own tracking on this and it's not ideal.

**Comment by Manishearth** [comment]
#220 and #221 did this.

#252 tracks moving over to it.
