### ISSUE TITLE
Tracking: Diplomat needs for mls-rs

### ISSUE THREAD

**Issue by Manishearth** [rust-diplomat/diplomat#534]
Android is looking at using Diplomat for [mls-rs](https://github.com/awslabs/mls-rs), with Kotlin or Java. Using this issue to consolidate all the things we think they'll need.

The tracking issue for Java support is https://github.com/rust-diplomat/diplomat/issues/144. We already have a Kotlin backend.

Features they absolutely need:
 - [ ] https://github.com/rust-diplomat/diplomat/issues/146

Safety things they may care about, that are currently not a huge deal for ICU4X (and thus deprioritized):
 - [ ] https://github.com/rust-diplomat/diplomat/issues/533
 - [ ] https://github.com/rust-diplomat/diplomat/issues/225

I can add more issues as needed.

cc @maurer @emarteca
